version: '3.8'
services:
  postgres:
    container_name: 'pg'
    image: postgres
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example-db 
volumes:
  pgdata:
